
/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

/*
 * File: /Applications/TextMate.app/Contents/MacOS/TextMate
 * Arch: Intel 80x86 (i386)
 */

@interface OakTextView (ExecuteCommand)
+ (id)defaultEnvironmentVariables;
- (id)wordAtCaret;
- (id)xmlRepresentationForSelection:(BOOL)fp8;
- (id)xmlRepresentation;
- (id)xmlRepresentationForSelection;
- (struct _NSPoint)positionForWindowUnderCaret;
- (id)environmentVariables;
- (void)extendSelectionInScope:(id)fp8;
- (void)selectCurrentScope:(id)fp8;
- (BOOL)selectFallbackInputForCommand:(id)fp8;
- (id)inputForCommand:(id)fp8 offset:(id *)fp12;
- (id)inputForCommand:(id)fp8;
- (void)executeCommandWithOptions:(id)fp8;
- (void)selectCommandResult:(id)fp8;
@end

@interface OakTextView (DragCommand)
- (BOOL)dropFile:(id)fp8;
@end

@interface OakTextView (CompletionMatches)
- (id)matchesForString:(id)fp8;
@end

@interface OakTextView (snippets)
- (void)leaveCodeSnippetEditing;
- (void)nextSnippetField:(id)fp8;
- (void)previousSnippetField:(id)fp8;
- (void)insertBacktab:(id)fp8;
- (void)deleteTabTrigger:(id)fp8;
- (BOOL)expandCodeSnippet:(id)fp8;
- (void)insertSnippet:(id)fp8;
- (void)insertSnippetWithOptions:(id)fp8;
@end

@interface OakTextView : NSView <NSTextInput>
{
    NSMutableArray *bindingObservers;
    OakDocument *document;
    struct action_map *actions;
    struct title_action_map *title_actions;
    struct ATSUI_render *render;
    NSMutableArray *macroRecordingBuffer;
    unsigned int viewChangeNesting;
    BOOL fillBackground;
    BOOL hasMarkedTextBeingEdited;
    BOOL didPressAlternateKey;
    NSDate *didPressAlternateKeyAtTime;
    unsigned int lastModifierFlags;
    BOOL leftMouseDown;
    BOOL isActivatingClick;
    BOOL isShowingDragCursor;
    NSTimer *initiateDragTimer;
    NSTimer *dragScrollTimer;
    NSEvent *activationEvent;
    struct _NSPoint mouseDownPoint;
    BOOL hasDragInside;
    BOOL dragIsLocal;
    NSTimer *blinkCaretTimer;
    BOOL isCaretHidden;
    struct _NSRect textFrame;
    float lineNumbersOffset;
    float bookmarksOffset;
    float foldingsOffset;
    NSTimer *showFoldedTextTimer;
    struct _NSRect showFoldedTextTriggerRectangle;
    OakTooltipWindow *showFoldedTextWindow;
    unsigned int showFoldedTextFromLine;
    unsigned int showFoldedTextToLine;
    OakWebPreviewManager *webPreviewManager;
    struct observer *webPreviewChangeObserver;
    BOOL pendingUpdateFunctionPopUp;
    NSTimer *updateFunctionPopUpTimer;
    NSArray *functionPopUp;
    id currentSymbol;
    struct observer *functionPopupChangeObserver;
    unsigned int clickCount;
    unsigned int mouseDownAtPositionLine;
    unsigned int mouseDownAtPositionColumn;
    unsigned int lineNumberDigits;
    OakISearchWindow *iSearchWindow;
    NSFont *font;
    _Bool hasCustomFont;
    unsigned int rightMargin;
    unsigned int tabSize;
    _Bool openFilesFolded;
    _Bool freehandedMode;
    _Bool overwriteMode;
    _Bool softWrap;
    _Bool hardWrap;
    _Bool autoIndent;
    _Bool indentedPaste;
    _Bool continuousSpellChecking;
    _Bool treatsSpacesAsTabs;
    _Bool smartTyping;
    _Bool foldings;
    _Bool lineNumbers;
    _Bool showSoftWrapInGutter;
    _Bool showBookmarksInGutter;
    _Bool expandSnippetsOnTab;
    _Bool antiAliasEnabled;
    _Bool showInvisibles;
    NSString *currentMode;
    id currentStyleSheet;
    id languageUUID;
    _Bool highlightWrapMargin;
    _Bool highlightCurrentLine;
    _Bool showWrapMargin;
}

+ (void)initialize;
- (void)undo:(id)fp8;
- (void)redo:(id)fp8;
- (void)toggleMacroRecording:(id)fp8;
- (void)recordMacroCommand:(SEL)fp8 argument:(id)fp12;
- (void)playMacroWithOptions:(id)fp8;
- (void)abortMacroRecording:(id)fp8;
- (id)toggleMacroRecordingMenuTitle;
- (BOOL)canAbortMacroRecording;
- (id)initWithFrame:(struct _NSRect)fp8;
- (void)dealloc;
- (void)applicationDidBecomeActiveNotification:(id)fp8;
- (void)userDefaultsDidChange:(id)fp8;
- (void)viewWillMoveToWindow:(id)fp8;
- (struct _NSRect)caretRefreshRectangle;
- (void)setSelectionNeedsDisplay:(BOOL)fp8;
- (BOOL)isOpaque;
- (BOOL)isFlipped;
- (BOOL)canBecomeKeyView;
- (BOOL)acceptsFirstResponder;
- (BOOL)resignFirstResponder;
- (id)document;
- (BOOL)becomeFirstResponder;
- (void)windowDidChangeKeyStatus:(id)fp8;
- (void)snapshotMetaData;
- (void)observeValueForKeyPath:(id)fp8 ofObject:(id)fp12 change:(id)fp16 context:(void *)fp20;
- (void)setDocument:(id)fp8;
- (void)myScrollRectToVisible:(id)fp8;
- (BOOL)validateMenuItem:(id)fp8;
- (id)performSelector:(SEL)fp8 withObject:(id)fp12;
- (BOOL)tryToPerform:(SEL)fp8 with:(id)fp12;
- (BOOL)respondsToSelector:(SEL)fp8;
- (void)keyDown:(id)fp8;
- (BOOL)hasMarkedText;
- (struct _NSRange)markedRange;
- (struct _NSRange)selectedRange;
- (id)validAttributesForMarkedText;
- (struct _NSRect)firstRectForCharacterRange:(struct _NSRange)fp8;
- (long)conversationIdentifier;
- (unsigned int)characterIndexForPoint:(struct _NSPoint)fp8;
- (id)attributedSubstringFromRange:(struct _NSRange)fp8;
- (void)doCommandBySelector:(SEL)fp8;
- (void)setMarkedText:(id)fp8 selectedRange:(struct _NSRange)fp12;
- (void)unmarkText;
- (void)insertText:(id)fp8;
- (void)pasteFromHistory:(id)fp8;
- (void)deleteBackward:(id)fp8;
- (void)deleteForward:(id)fp8;
- (void)deleteToEndOfParagraph:(id)fp8;
- (void)flagsChanged:(id)fp8;
- (void)centerSelectionInVisibleArea:(id)fp8;
- (void)setFont:(id)fp8;
- (void)makeTextLarger:(id)fp8;
- (void)makeTextSmaller:(id)fp8;
- (BOOL)canMakeFontBigger;
- (BOOL)canMakeFontSmaller;
- (BOOL)hasSelection;
- (unsigned long)internalReplaceAll:(id)fp8 error:(id *)fp12;
- (void)replaceAll:(id)fp8;
- (void)replaceAllInSelection:(id)fp8;
- (id)findWithOptions:(id)fp8;
- (id)validRequestorForSendType:(id)fp8 returnType:(id)fp12;
- (BOOL)writeSelectionToPasteboard:(id)fp8 types:(id)fp12;
- (BOOL)readSelectionFromPasteboard:(id)fp8;
- (void)setupBlinkCaretTimer;
- (void)blinkCaret:(id)fp8;
- (void)showCaret;
- (void)centerCaretInDisplay:(id)fp8;
- (struct pos)eventPosition:(id)fp8;
- (void)changeToDragPointer:(id)fp8;
- (void)resetCursorRects;
- (BOOL)acceptsFirstMouse:(id)fp8;
- (BOOL)shouldDelayWindowOrderingForEvent:(id)fp8;
- (int)dragDelay;
- (void)rightMouseDown:(id)fp8;
- (void)mouseDown:(id)fp8;
- (void)mouseUp:(id)fp8;
- (void)startDragForEvent:(id)fp8;
- (void)autoscrollTimerFired:(id)fp8;
- (void)mouseDragged:(id)fp8;
- (void)scrollViewByX:(float)fp8 byY:(long)fp12;
- (void)scrollLineUp:(id)fp8;
- (void)scrollLineDown:(id)fp8;
- (void)scrollColumnLeft:(id)fp8;
- (void)scrollColumnRight:(id)fp8;
- (void)setHasDragInside:(BOOL)fp8;
- (unsigned int)draggingSourceOperationMaskForLocal:(BOOL)fp8;
- (unsigned int)dragOperationForInfo:(id)fp8;
- (unsigned int)draggingEntered:(id)fp8;
- (unsigned int)draggingUpdated:(id)fp8;
- (void)draggingExited:(id)fp8;
- (BOOL)prepareForDragOperation:(id)fp8;
- (BOOL)performDragOperation:(id)fp8;
- (void)concludeDragOperation:(id)fp8;
- (void)changeSpelling:(id)fp8;
- (void)movePageUp:(id)fp8;
- (void)movePageDown:(id)fp8;
- (void)movePageUpAndModifySelection:(id)fp8;
- (void)movePageDownAndModifySelection:(id)fp8;
- (BOOL)canReopenWithEncoding;
- (BOOL)reopenWithEncodingIsChecked:(id)fp8;
- (void)reopenWithEncoding:(id)fp8;
- (void)fillSelectionWithString:(id)fp8;
- (void)performFillSelectionWithAction:(id)fp8;
- (void)fillSelectionWith:(id)fp8;
- (void)recalcFrameSize;
- (void)setFrame:(struct _NSRect)fp8;
- (void)updateScreenWidth;
- (void)scrollPageUp:(id)fp8;
- (void)scrollPageDown:(id)fp8;
- (void)scrollToBeginningOfDocument:(id)fp8;
- (void)scrollToEndOfDocument:(id)fp8;
- (id)stringValue;
- (id)currentMode;
- (void)setCurrentMode:(id)fp8;
- (id)_getOakTextViewInstance:(id)fp8;

@end

@interface OakTextView (bindings)
- (void)bind:(id)fp8 toObject:(id)fp12 withKeyPath:(id)fp16 options:(id)fp20;
- (void)unbind:(id)fp8;
- (void)updateValue:(id)fp8 forKey:(id)fp12;
- (void)setMacroRecordingBuffer:(id)fp8;
@end

@interface OakTextView (Bookmarks)
- (void)toggleCurrentBookmark:(id)fp8;
- (id)toggleCurrentBookmarkMenuTitle;
- (void)goToNextBookmark:(id)fp8;
- (void)goToPreviousBookmark:(id)fp8;
@end

@interface OakTextView (drawRect)
- (struct _NSPoint)iteratorPosition:;
- (void)toggleShowInvisibles:(id)fp8;
- (id)toggleShowInvisiblesMenuTitle;
- (void)drawRect:(struct _NSRect)fp8;
- (void)setupTextFrame;
- (unsigned int)typeForLine:(id)fp8 withPatterns:(id [4])fp12;
- (int)currentIndentForContent:(id)fp8 atLine:(unsigned long)fp12;
- (int)indentForCurrentLine;
- (unsigned long)currentIndent;
- (unsigned long)indentLine:(unsigned long)fp8;
- (id)indentMenuTitle;
- (void)indent:(id)fp8;
@end

@interface OakTextView (ExecuteSelection)
- (void)executeSelectionInsertingOutput:(id)fp8;
- (void)executeSelectionAppendingOutput:(id)fp8;
- (void)executeSelectionReplacingSelection:(id)fp8;
@end

@interface OakTextView (Extension)
- (void)selectFollowingKeyView:(id)fp8;
- (void)selectPrecedingKeyView:(id)fp8;
- (BOOL)takeRightMarginFromIsChecked:(id)fp8;
- (void)setContinuousSpellCheckingEnabled:(BOOL)fp8;
- (void)setExpandSnippetsOnTab:(BOOL)fp8;
- (void)setSoftWrap:(BOOL)fp8;
- (void)setFreehandedEdit:(BOOL)fp8;
- (void)setTabSize:(unsigned long)fp8;
- (void)setRightMargin:(unsigned long)fp8;
- (void)setOverwriteMode:(BOOL)fp8;
- (void)setOpenFilesFolded:(BOOL)fp8;
- (void)setShowSoftWrapInGutter:(BOOL)fp8;
- (void)setShowBookmarksInGutter:(BOOL)fp8;
- (unsigned long)tabSize;
- (BOOL)freehandedEdit;
- (void)toggleFreehandedEdit:(id)fp8;
- (BOOL)isContinuousSpellCheckingEnabled;
- (void)toggleContinuousSpellChecking:(id)fp8;
- (BOOL)toggleContinuousSpellCheckingIsChecked:(id)fp8;
- (BOOL)expandSnippetsOnTab;
- (void)toggleExpandSnippetsOnTab:(id)fp8;
- (BOOL)toggleExpandSnippetsOnTabIsChecked:(id)fp8;
- (BOOL)canToggleHardWrap;
- (BOOL)overwriteMode;
- (void)toggleOverwriteMode:(id)fp8;
- (BOOL)softWrap;
- (void)toggleSoftWrap:(id)fp8;
- (BOOL)autoIndent;
- (BOOL)hardWrap;
- (BOOL)indentedPaste;
- (void)setAutoIndent:(BOOL)fp8;
- (void)setHardWrap:(BOOL)fp8;
- (void)setIndentedPaste:(BOOL)fp8;
- (void)toggleAutoIndent:(id)fp8;
- (void)toggleHardWrap:(id)fp8;
- (void)toggleIndentedPaste:(id)fp8;
- (BOOL)openFilesFolded;
- (void)toggleOpenFilesFolded:(id)fp8;
- (BOOL)toggleOpenFilesFoldedIsChecked:(id)fp8;
- (BOOL)canToggleOpenFilesFolded;
- (BOOL)showSoftWrapInGutter;
- (void)toggleShowSoftWrapInGutter:(id)fp8;
- (BOOL)toggleShowSoftWrapInGutterIsChecked:(id)fp8;
- (BOOL)showBookmarksInGutter;
- (void)toggleShowBookmarksInGutter:(id)fp8;
- (BOOL)toggleShowBookmarksInGutterIsChecked:(id)fp8;
- (void)takeTabSizeFrom:(id)fp8;
- (BOOL)takeTabSizeFromIsChecked:(id)fp8;
- (void)takeRightMarginFrom:(id)fp8;
- (void)insertNewline:(id)fp8;
- (void)setSoftTabs:(BOOL)fp8;
- (BOOL)softTabs;
- (BOOL)treatsSpacesAsTabs;
- (void)setSmartTyping:(BOOL)fp8;
- (BOOL)smartTyping;
- (void)toggleSmartTyping:(id)fp8;
- (void)setAntiAliasEnabled:(BOOL)fp8;
- (BOOL)antiAliasEnabled;
- (void)toggleAntiAliasEnabled:(id)fp8;
- (void)setLineNumbers:(BOOL)fp8;
- (BOOL)lineNumbers;
- (void)toggleLineNumbers:(id)fp8;
- (void)insertTab:(id)fp8;
- (void)goToLineNumber:(id)fp8;
- (void)goToColumnNumber:(id)fp8;
- (void)selectToLine:(id)fp8 andColumn:(id)fp12;
- (void)setFoldingsEnabled:(BOOL)fp8;
- (BOOL)foldingsEnabled;
- (void)toggleFoldingsEnabled:(id)fp8;
- (id)toggleFoldingMenuTitle;
- (BOOL)canToggleFolding;
- (BOOL)canFoldAllAtLevel;
- (BOOL)canUnfoldAllAtLevel;
- (void)foldAllAtLevel:(id)fp8;
- (void)foldSelection:(id)fp8;
- (void)toggleFolding:(id)fp8;
- (BOOL)toggleFreehandedEditIsChecked:(id)fp8;
- (BOOL)toggleOverwriteModeIsChecked:(id)fp8;
- (BOOL)toggleSoftWrapIsChecked:(id)fp8;
- (BOOL)toggleTreatsSpacesAsTabsIsChecked:(id)fp8;
- (BOOL)toggleSmartTypingIsChecked:(id)fp8;
- (BOOL)toggleFoldingsEnabledIsChecked:(id)fp8;
- (BOOL)toggleHardWrapIsChecked:(id)fp8;
- (BOOL)toggleIndentedPasteIsChecked:(id)fp8;
- (BOOL)toggleLineNumbersIsChecked:(id)fp8;
- (BOOL)toggleAntiAliasEnabledIsChecked:(id)fp8;
- (void)selectBlock:(id)fp8;
- (BOOL)canNextCompletion;
- (BOOL)canPreviousCompletion;
@end

@interface OakTextView (ScopedSettings)
- (void)setScopedValue:(id)fp8 forKey:(id)fp12 inDomain:(id)fp16;
- (id)scopedValueForKey:(id)fp8 inDomain:(id)fp12;
@end

@interface OakTextView (FoldingTooltip)
- (void)viewDidMoveToWindow;
- (void)showFoldedText:(id)fp8;
- (BOOL)abortShowingFoldedText:(id)fp8;
- (void)mouseMoved:(id)fp8;
- (void)orderFrontWebPreview:(id)fp8;
@end

@interface OakTextView (ISearch)
- (id)incrementalSearchWindow;
- (void)ISIM_incrementalSearch:(id)fp8;
- (void)ISIM_reverseIncrementalSearch:(id)fp8;
- (BOOL)findNextIncrementalSearchString:(BOOL)fp8;
- (BOOL)findPreviousIncrementalSearchString:(BOOL)fp8;
@end

@interface OakTextView (OakTextViewPageUpDown)
- (void)pageUp:(id)fp8;
- (void)pageDown:(id)fp8;
- (void)pageUpAndModifySelection:(id)fp8;
- (void)pageDownAndModifySelection:(id)fp8;
@end

@interface OakTextViewPrinting : NSView
{
    OakTextView *textView;
    NSMatrix *paperOrnaments;
    unsigned int linesPerPage;
    unsigned int numberOfPages;
    struct vector<std::vector<text::char_t, std::allocator<text::char_t>>, std::allocator<std::vector<text::char_t, std::allocator<text::char_t>>>> *lines;
    struct ATSUI_render *render;
}

- (id)initWithTextView:(id)fp8;
- (void)dealloc;
- (BOOL)knowsPageRange:(struct _NSRange *)fp8;
- (void)beginPageInRect:(struct _NSRect)fp8 atPlacement:(struct _NSPoint)fp24;
- (void)drawPageBorderWithSize:(struct _NSSize)fp8;
- (void)drawRect:(struct _NSRect)fp8;
- (BOOL)isFlipped;
- (struct _NSRect)rectForPage:(int)fp8;
- (float)calculatePrintWidth;
- (float)calculatePrintHeight;

@end

@interface OakTextView (OakTextViewPrinting)
- (void)printOperationDidRun:(id)fp8 success:(BOOL)fp12 contextInfo:(id)fp16;
- (void)printDocument:(id)fp8;
@end

@interface OakTextView (SpellChecking)
- (void)ignoreSpelling:(id)fp8;
- (void)contextMenuIgnoreSpelling:(id)fp8;
- (void)contextMenuLearnSpelling:(id)fp8;
- (void)checkSpelling:(id)fp8;
- (void)showGuessPanel:(id)fp8;
- (void)correctWord:(id)fp8;
- (void)selectMisspelledWordAt:;
- (id)contextMenu;
- (id)menuForEvent:(id)fp8;
- (void)showContextMenu:(id)fp8;
@end

@interface OakTextView (StyleSheet)
+ (void)load;
- (void)goToSymbol:(id)fp8;
- (id)currentStyleSheet;
- (void)themeDidChange:(id)fp8;
- (void)setCurrentStyleSheet:(id)fp8;
- (id)scopeForContext:;
- (id)stylesForContext:;
-     // Error parsing type: 12@0:48, name: graphPathForIterator:
-     // Error parsing type: 12@0:4c8, name: graphPathForCaretWait:
- (id)currentContext;
- (id)currentContext:(id)fp8;
- (id)stylesForCaretWait:(BOOL)fp8;
- (id)stylesForCaret;
- (void)resetDisplay:(id)fp8;
- (id)languageForUUID:(id)fp8;
- (id)languageChoiceForFile:(id)fp8 withFirstLine:(id)fp12;
- (id)languageChoiceForCurrentFile;
- (id)suggestedExtensionForDocument;
- (BOOL)storedSoftWrapSetting;
- (int)storedTabSizeSetting;
- (BOOL)storedSoftTabsSetting;
- (BOOL)storedContinuousSpellCheckingSetting;
- (void)initializeSettings;
- (void)learnFileAssociation:(id)fp8;
- (void)changeLanguageTo:(id)fp8 andLearn:(BOOL)fp12;
- (void)changeLanguageToAndLearn:(id)fp8;
- (void)languagesDidChange:(id)fp8;
- (void)preferencesDidChange:(id)fp8;
- (void)setCurrentSymbol:(id)fp8;
- (void)buildFunctionPopUp;
- (id)functionPopUp;
- (void)delayedUpdateFunctionPopUp:(id)fp8;
- (void)updateFunctionPopUp:(BOOL)fp8;
@end

@interface OakTextView (DictionaryInput)
- (id)accessibilityHitTest:(struct _NSPoint)fp8;
- (id)accessibilityAttributeNames;
- (id)accessibilityAttributeValue:(id)fp8;
- (id)accessibilityAttributeValue:(id)fp8 forParameter:(id)fp12;
@end
